version: '3'
services:
  web:
    image: liftit_user_umbrella:v1
    build: .
    command: mix phx.server
    volumes:
      - .:/liftit_user_umbrella
    ports:
      - "4000:4000"
    env_file: .env
    depends_on:
      - db
      - rabbitmq
    links:
      - db:db
      - rabbitmq:rabbitmq

  db:
    image: postgres:9.6
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./.data/rabbitmq:/var/lib/rabbitmq
      - ./conf/myrabbit.conf:/etc/rabbitmq/rabbitmq.conf
